import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

const pageUrl = new URL('../pages/app/admin/programs/[programId]/cohorts/[cohortId].vue', import.meta.url)

assert.equal(existsSync(pageUrl), true, 'Admin cohort workspace route should exist.')

const pageSource = readFileSync(pageUrl, 'utf8')

assert.match(pageSource, /permissions:\s*\['admin:programs'\]/, 'Cohort workspace should stay under company program admin access.')
assert.match(pageSource, /loadCohort/, 'Workspace should load the selected cohort.')
assert.match(pageSource, /loadParticipants/, 'Workspace should load cohort participants.')
assert.match(pageSource, /loadJoinRequests/, 'Workspace should load cohort join requests.')
assert.match(pageSource, /loadCircles/, 'Workspace should load common-interest circles.')
assert.match(pageSource, /loadDashboard/, 'Workspace should load the cohort dashboard.')
assert.match(pageSource, /CompanyProgramCohortEditorDialog/, 'Workspace should support editing cohort settings.')
assert.match(pageSource, /confirmParticipant/, 'Workspace should support confirming participants.')
assert.match(pageSource, /rejectParticipant/, 'Workspace should support rejecting participants.')
assert.match(pageSource, /resolveDuplicate/, 'Workspace should expose duplicate review actions.')
assert.match(pageSource, /confirmJoinRequest/, 'Workspace should support confirming join requests.')
assert.match(pageSource, /rejectJoinRequest/, 'Workspace should support rejecting join requests.')
assert.match(pageSource, /addRosterParticipants/, 'Workspace should support partner-admin roster uploads.')
assert.match(pageSource, /isRosterDialogOpen/, 'Workspace should open roster upload from a dialog.')
assert.match(pageSource, /v-model:open="isRosterDialogOpen"/, 'Roster upload should render inside a dialog.')
assert.match(pageSource, /parseRosterCsv/, 'Workspace should parse pasted or uploaded roster CSV data.')
assert.match(pageSource, /Upload roster/, 'Workspace should expose an Upload roster action.')
assert.match(pageSource, /Add participants/, 'Workspace should expose Add participants language for the cohort roster.')
assert.match(pageSource, /recordPlenaryAttendance/, 'Workspace should support plenary attendance recording.')
assert.match(pageSource, /suggestCircles/, 'Workspace should request circle suggestions.')
assert.match(pageSource, /createCircle/, 'Workspace should support creating circles.')
assert.match(pageSource, /placeParticipant/, 'Workspace should place participants into circles.')
assert.match(pageSource, /isCreateCircleDialogOpen/, 'Manual circle creation should be opened from a dialog trigger.')
assert.match(pageSource, /v-model:open="isCreateCircleDialogOpen"/, 'Manual circle creation should render inside a dialog.')
assert.doesNotMatch(pageSource, /<CardTitle>Create Circle<\/CardTitle>/, 'Manual circle creation should not remain as an inline card form.')
assert.match(pageSource, /openAddMenteesDialog/, 'Circle cards should expose a scoped add-mentees flow.')
assert.match(pageSource, /Add mentees/, 'Circle cards should show an Add mentees action.')
assert.match(pageSource, /placeParticipantInCircle\(addMenteesCircle\.id,\s*participant\)/, 'Add mentees should place a selected unplaced participant into the active circle.')
assert.match(pageSource, /moveMembership/, 'Workspace should move circle members.')
assert.match(pageSource, /removeMembership/, 'Workspace should remove circle members.')
assert.match(pageSource, /finalizeCircles/, 'Workspace should finalize circles.')
assert.match(pageSource, /activeTab = 'circles'/, 'Workspace should include a circles tab.')
assert.match(pageSource, /Unplaced participants/, 'Circle workspace should expose unplaced participants.')
assert.match(pageSource, /Confirm circles as final/, 'Circle workspace should expose finalization action.')
assert.match(pageSource, /value > 1 \? value : value \* 100/, 'Dashboard percentages should accept backend percent values and fractional fallback values.')
assert.match(pageSource, /No active mentees are in this cohort yet/, 'Circle empty state should explain that participants must be added before mentees can be placed.')

console.log('B2B2C admin cohort workspace UI verified.')
