import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

const pageUrl = new URL('../pages/app/admin/cohorts/[cohortId].vue', import.meta.url)

assert.equal(existsSync(pageUrl), true, 'Admin cohort workspace route should exist.')

const pageSource = readFileSync(pageUrl, 'utf8')

assert.match(pageSource, /permissions:\s*\['admin:program-cohorts'\]/, 'Cohort workspace should use cohort admin access.')
assert.match(pageSource, /loadCohort/, 'Workspace should load the selected cohort.')
assert.match(pageSource, /loadParticipants/, 'Workspace should load cohort participants.')
assert.match(pageSource, /loadJoinRequests/, 'Workspace should load cohort join requests.')
assert.match(pageSource, /loadCircles/, 'Workspace should load common-interest circles.')
assert.match(pageSource, /loadDashboard/, 'Workspace should load the cohort dashboard.')
assert.match(pageSource, /CompanyProgramCohortEditorDialog/, 'Workspace should support editing cohort settings.')
assert.match(pageSource, /confirmParticipant/, 'Workspace should support confirming participants.')
assert.match(pageSource, /rejectParticipant/, 'Workspace should support rejecting participants.')
assert.match(pageSource, /resolveDuplicate/, 'Workspace should expose duplicate review actions.')
assert.match(pageSource, /confirmJoinRequest/, 'Workspace should support confirming join requests.')
assert.match(pageSource, /rejectJoinRequest/, 'Workspace should support rejecting join requests.')
assert.match(pageSource, /addRosterParticipants/, 'Workspace should support partner-admin roster uploads.')
assert.match(pageSource, /isRosterDialogOpen/, 'Workspace should open roster upload from a dialog.')
assert.match(pageSource, /v-model:open="isRosterDialogOpen"/, 'Roster upload should render inside a dialog.')
assert.match(pageSource, /useCompanyProgramsStore/, 'Add participants should load the parent program employee roster.')
assert.match(pageSource, /loadProgramParticipants/, 'Add participants should request existing program participants through the program store.')
assert.match(pageSource, /programRosterParticipants/, 'Add participants should expose existing program employees as a roster source.')
assert.match(pageSource, /selectedProgramParticipantIds/, 'Add participants should track selected existing program participants.')
assert.match(pageSource, /profileId:\s*participant\.profileId/, 'Adding from the program roster should post profile IDs to the cohort roster API.')
assert.match(pageSource, /parseRosterCsv/, 'Workspace should parse pasted or uploaded roster CSV data.')
assert.match(pageSource, /import \* as XLSX from 'xlsx'/, 'Workspace should use the xlsx library for Excel roster files.')
assert.match(pageSource, /downloadRosterTemplate/, 'Workspace should provide a downloadable Excel roster template.')
assert.match(pageSource, /XLSX\.utils\.aoa_to_sheet/, 'Roster template should be generated from structured rows.')
assert.match(pageSource, /XLSX\.writeFile/, 'Roster template should download as an Excel workbook.')
assert.match(pageSource, /XLSX\.read/, 'Workspace should parse uploaded Excel roster workbooks.')
assert.match(pageSource, /accept="\.csv,\.xlsx,\.xls,text\/csv/, 'Roster upload should accept CSV and Excel files.')
assert.match(pageSource, /Participants will be notified/, 'Add participants dialog should make cohort notifications explicit.')
assert.match(pageSource, /Upload roster/, 'Workspace should expose an Upload roster action.')
assert.match(pageSource, /From program roster/, 'Workspace should allow adding existing program employees to a cohort.')
assert.match(pageSource, /Add participants/, 'Workspace should expose Add participants language for the cohort roster.')
assert.match(pageSource, /recordPlenaryAttendance/, 'Workspace should support plenary attendance recording.')
assert.match(pageSource, /suggestCircles/, 'Workspace should request circle suggestions.')
assert.match(pageSource, /createCircle/, 'Workspace should support creating circles.')
assert.match(pageSource, /placeParticipant/, 'Workspace should place participants into circles.')
assert.match(pageSource, /circleEligibleParticipants[\s\S]*CONFIRMED/, 'Confirmed participants should be eligible for manual circle placement.')
assert.match(pageSource, /isCreateCircleDialogOpen/, 'Manual circle creation should be opened from a dialog trigger.')
assert.match(pageSource, /v-model:open="isCreateCircleDialogOpen"/, 'Manual circle creation should render inside a dialog.')
assert.doesNotMatch(pageSource, /<CardTitle>Create Circle<\/CardTitle>/, 'Manual circle creation should not remain as an inline card form.')
assert.match(pageSource, /openAddMenteesDialog/, 'Circle cards should expose a scoped add-mentees flow.')
assert.match(pageSource, /Add mentees/, 'Circle cards should show an Add mentees action.')
assert.match(pageSource, /placeParticipantInCircle\(addMenteesCircle\.id,\s*participant\)/, 'Add mentees should place a selected unplaced participant into the active circle.')
assert.match(pageSource, /moveMembership/, 'Workspace should move circle members.')
assert.match(pageSource, /removeMembership/, 'Workspace should remove circle members.')
assert.match(pageSource, /finalizeCircles/, 'Workspace should finalize circles.')
assert.match(pageSource, /activeTab = 'circles'/, 'Workspace should include a circles tab.')
assert.match(pageSource, /Unplaced participants/, 'Circle workspace should expose unplaced participants.')
assert.match(pageSource, /Confirm circles as final/, 'Circle workspace should expose finalization action.')
assert.match(pageSource, /value > 1 \? value : value \* 100/, 'Dashboard percentages should accept backend percent values and fractional fallback values.')
assert.match(pageSource, /No active mentees are in this cohort yet/, 'Circle empty state should explain that participants must be added before mentees can be placed.')

console.log('B2B2C admin cohort workspace UI verified.')
