import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

const detailUrl = new URL('../pages/app/admin/programs/[programId]/index.vue', import.meta.url)
const standaloneUrl = new URL('../pages/app/admin/cohorts/index.vue', import.meta.url)
const listUrl = new URL('../components/app/admin/cohorts/CompanyProgramCohortList.vue', import.meta.url)
const editorUrl = new URL('../components/app/admin/cohorts/CompanyProgramCohortEditorDialog.vue', import.meta.url)
const roleManagerUrl = new URL('../utils/roleManager.ts', import.meta.url)
const authTypesUrl = new URL('../types/auth.ts', import.meta.url)

assert.equal(existsSync(listUrl), true, 'Cohort list component should remain available for focused program-scoped reuse.')
assert.equal(existsSync(editorUrl), true, 'Cohort create/edit should use a focused dialog component.')
assert.equal(existsSync(standaloneUrl), true, 'Admin cohorts should have a standalone route.')

const detailSource = readFileSync(detailUrl, 'utf8')
const standaloneSource = readFileSync(standaloneUrl, 'utf8')
const listSource = readFileSync(listUrl, 'utf8')
const editorSource = readFileSync(editorUrl, 'utf8')
const roleManagerSource = readFileSync(roleManagerUrl, 'utf8')
const authTypesSource = readFileSync(authTypesUrl, 'utf8')

assert.match(detailSource, /activeTab = 'cohorts'/, 'Program detail tabs should include Cohorts.')
assert.doesNotMatch(detailSource, /<CompanyProgramCohortList/, 'Program detail should not render the operational cohort list.')
assert.match(detailSource, /useCompanyProgramCohortsStore/, 'Program detail should read cohort counts from the cohort store.')
assert.match(detailSource, /const cohortTabCount = computed\(\(\) =>/, 'Program detail should compute the Cohorts tab badge from loaded cohorts.')
assert.match(detailSource, /cohorts\.value\.filter\([\s\S]*cohort\.companyProgramId === programId\.value/, 'Program detail should count cohorts for the selected program only.')
assert.match(detailSource, /Cohorts[\s\S]*<span>{{ cohortTabCount }}<\/span>/, 'Cohorts tab badge should use the loaded cohort collection count.')
assert.match(detailSource, /openProgramCohorts[\s\S]*\/app\/admin\/cohorts\?programId=\$\{programId\.value\}/, 'Program detail should link to the standalone cohorts page filtered by program.')
assert.doesNotMatch(detailSource, /Cohorts[\s\S]{0,160}<span>{{ selectedProgram\?\.cohortCount \|\| 0 }}<\/span>/, 'Cohorts tab badge should not depend on the optional program detail cohortCount aggregate.')
assert.match(standaloneSource, /loadCompanyCohorts\(companyId\.value\)/, 'Standalone cohort list should load all company cohorts.')
assert.match(standaloneSource, /selectedProgramFilter/, 'Standalone cohort list should support program filtering.')
assert.match(standaloneSource, /CompanyProgramCohortEditorDialog/, 'Standalone cohort list should expose the create cohort dialog.')
assert.match(listSource, /loadCohorts/, 'Cohort list should load cohorts through the cohort store.')
assert.match(listSource, /Create cohort/, 'Cohort list should expose a Create cohort action.')
assert.match(listSource, /navigateTo\(`\/app\/admin\/cohorts\/\$\{cohort\.id\}`\)/, 'Cohort cards should open the standalone cohort detail route.')
assert.match(editorSource, /selfJoinEnabled/, 'Cohort editor should expose self-join settings.')
assert.match(editorSource, /circleMinSize/, 'Cohort editor should expose circle min size.')
assert.match(editorSource, /circleMaxSize/, 'Cohort editor should expose circle max size.')
assert.match(authTypesSource, /MANAGE_PROGRAM_COHORTS:\s*'admin:program-cohorts'/, 'Auth permission constants should include program cohort management.')
assert.match(roleManagerSource, /admin:program-cohorts/, 'Role manager should register cohort permission.')
assert.match(roleManagerSource, /'\/app\/admin\/programs\/\*':\s*\['admin:programs'[\s\S]*\]/, 'Existing program routes should remain accessible to program admins.')

console.log('B2B2C admin cohort list UI verified.')
