import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const pageSource = readFileSync(new URL('../pages/app/admin/mentors.vue', import.meta.url), 'utf8')
const inviteDialogSource = readFileSync(new URL('../components/app/admin/mentors/InviteCompanyMentorDialog.vue', import.meta.url), 'utf8')
const importDialogSource = readFileSync(new URL('../components/app/admin/mentors/ImportCompanyMentorsDialog.vue', import.meta.url), 'utf8')
const visibilityDialogSource = readFileSync(new URL('../components/app/admin/mentors/EditCompanyMentorVisibilityDialog.vue', import.meta.url), 'utf8')

assert.match(pageSource, /useCompanyMentorsStore/)
assert.match(pageSource, /import CompanyMentorStatusBadge from '~\/components\/app\/admin\/mentors\/CompanyMentorStatusBadge\.vue'/)
assert.match(pageSource, /import EditCompanyMentorVisibilityDialog from '~\/components\/app\/admin\/mentors\/EditCompanyMentorVisibilityDialog\.vue'/)
assert.match(pageSource, /import ImportCompanyMentorsDialog from '~\/components\/app\/admin\/mentors\/ImportCompanyMentorsDialog\.vue'/)
assert.match(pageSource, /import InviteCompanyMentorDialog from '~\/components\/app\/admin\/mentors\/InviteCompanyMentorDialog\.vue'/)
assert.match(pageSource, /InviteCompanyMentorDialog/)
assert.match(pageSource, /ImportCompanyMentorsDialog/)
assert.match(pageSource, /EditCompanyMentorVisibilityDialog/)
assert.match(pageSource, /Pending invites/)
assert.match(pageSource, /Company-bookable/)
assert.match(pageSource, /Email delivery/)
assert.match(pageSource, /WhatsApp delivery/)
assert.match(pageSource, /Public approval/)
assert.match(pageSource, /resendInvitation/)
assert.match(pageSource, /canManageCompanyMentors/)
assert.match(pageSource, /hasStoredCompanyMentorAdminAccess/)
assert.match(pageSource, /localStorage\.getItem\('role'\)/)
assert.match(pageSource, /parsedProfile\?\.role/)
assert.match(pageSource, /permissions\?\.some\(\(permission: any\) => permission\?\.id === 'admin:mentors'\)/)
assert.match(pageSource, /Company admin access is required to invite or import company mentors/)
assert.match(pageSource, /<TabsContent value="company" v-if="hasCompanyMentorAdminAccess"/)
assert.doesNotMatch(pageSource, /Invite mentor[\s\S]{0,180}:disabled="!canManageCompanyMentors"/)
assert.doesNotMatch(pageSource, /Import[\s\S]{0,180}:disabled="!canManageCompanyMentors"/)

assert.match(inviteDialogSource, /email/)
assert.match(inviteDialogSource, /phone/)
assert.match(inviteDialogSource, /COMPANY_PRIVATE/)
assert.match(inviteDialogSource, /PROGRAM_RESTRICTED/)
assert.match(inviteDialogSource, /PUBLIC_REQUESTED/)
assert.match(inviteDialogSource, /Company admin context is required before sending mentor invites/)
assert.match(inviteDialogSource, /:disabled="[^"]*!props\.companyId/)
assert.match(inviteDialogSource, /throw new Error\('Company admin context is required before sending mentor invites'\)/)

assert.match(importDialogSource, /validateImport/)
assert.match(importDialogSource, /importMentors/)
assert.match(importDialogSource, /rowNumber/)
assert.match(importDialogSource, /:disabled="[^"]*errors/)

assert.match(visibilityDialogSource, /updateVisibility/)
assert.match(visibilityDialogSource, /companyProgramIds/)

console.log('Company mentor enrollment UI verified.')
